<?php
 
function weather_block_info() {
	$blocs['weather_block'] = array(
		'info' => "Out weather block",
	);
	return $blocs;
}
 
function weather_block_view($delta = '') {
	switch($delta){
		case 'weather':
			$block['content'] = block_function();
			break;
	}
	return $block;
}
 
function block_function(){
	
	$output = theme('weather_template');
	return $output;
}
 
function weather_theme() {
	return array(
		'weather_template' => array(
			'template' => 'weather_template',
		)
	);
}

